### ISSUE TITLE
About the latest changes to the ppb conversion function.

### ISSUE THREAD

**Issue by ferreiradiego** [ostaquet/Arduino-MQ131-driver#25]
In the last version, some changes was did.
I didn't get it why the code `return convert(9.4783 * pow(ratio, 2.3348), PPB, unit);` was modified to `return convert((10.66435681 * pow(ratio, 2.25889394) - 10.66435681), PPB, unit);`. If you compare the table below, you can see that the values in ppb below 200 differs a lot and above 200 the second function it's better.

ppb | Rs/R0 O3 | y = 9,4783x2,3348 | y = 10,66435681x2,25889394 - 10,66435681
-- | -- | -- | --
10 | 1,12 | 12,34936679 | 3,111320483
50 | 1,9 | 42,41938405 | 34,79355558
100 | 2,5 | 80,50832346 | 73,83218626
200 | 3,8 | 213,9977425 | 206,9083026
500 | 5,6 | 529,175655 | 511,746348
1000 | 7,5 | 1046,703047 | 999,9960501

The function in `return convert((10.66435681 * pow(ratio, 2.25889394) - 10.66435681), PPB, unit);` is really better than the other?

PS.: I get it that the a and b coeficients changed, but the dubt is in the function with the subtraction of coeficient a.

If also @nitram147 may help me in my doubt I appreciate it

**Comment by nitram147** [comment]
There is a need to use function like:
<img src="https://render.githubusercontent.com/render/math?math=a\times x^{b}%2Bc">
Instead of previous designed function:
<img src="https://render.githubusercontent.com/render/math?math=a\times x^{b}">
With the latter one (fucntion without "+c") it's not possible to get zero ppb when the ratio is equal to one. 
So you will get always some concentration (at least 9.4783) in case that you use the latter function (function withou "+c").
In **extras/datasheet/** you can find files **mq131_high_fit.py** and ****mq131_low_fit.py**** which I designed for calculation of required a,b,c coeficients. If you want to make the function fit the lower concentration correctly (trade-off would be that it will have bigger error on higher concentrations) you can play with **sigma** parameters in mentioned python script. Right now the higher fitting priority is set-uped for the first and last point of the curve (0 concentration, max concentration). You can add higher priority also to 10, 50 ppm/ppb points.
