### ISSUE TITLE
Calibration to Zero

### ISSUE THREAD

**Issue by chazbevo** [ostaquet/Arduino-MQ131-driver#28]
Thank you for the new commit from 7/7.

Since I have a high-concentration sensor, in the "calibrate.ino", I changed the module time to "HIGH_CONCENTRATION" in the MQ131.begin() statement.  Is that correct?

Within the same statement, I also changed the RL setting to the value of my resistor as measured by my Ohm meter -- 10,000 ohms.

The calibration resulted in an R0 of 470 ohms, time to heat of 75 seconds, and Ozone level values of 2-3 ppm at 7:30 in the morning at 23 C with the sensor just outside my window.  How does one calibrate the sensor to zero?  Do I vary the RL value?  Right now, I'm running a 10K resistor....should I use a 1M ohm resistor or something in between?  Thanks again for your prompt responses.

**Comment by ostaquet** [comment]
With a high concentration sensor, you will probably never go to zero because it is designed for high concentration of ozone. Below 10ppm, you will have no detection with the high concentration sensor. If you want to measure lower concentration, you should use the low concentration sensor (detection start at 10ppb).

So, I'm not surprised that you're around 2-3 ppm with the high concentration sensor in fresh air. An higher load resistance will not help.
