### ISSUE TITLE
MQ131 analog out less than 1V

### ISSUE THREAD

**Issue by oeyaugust** [ostaquet/Arduino-MQ131-driver#43]
Hi, 

I wonder if you have experienced a situation when the voltage output from the sensor is less than 1V. 

In my case, I used MQ131 low concentration (black case) with PCB breakout that provides 4 connecting pins (Vcc, Gnd, Do, and Ao). I pre-heated the device for 3 days, then read the Ao using a basic AnalogRead function. The reading is 0.27V, which is unexpected. 

I checked the sensor and the PCB breakout for any visual damage. I traced the circuit too. But, I could not find any issue. 

I hope you be pleased to share your opinion or to suggest any possible solution. I look forward to hearing from you. Thank you.

Regards

**Comment by ostaquet** [comment]
I don't have an MQ131 close to me at the moment to perform a test and I never took the measure in V.

The sampled value depends on the ratio RL on R0 and those R values are computed through the Ohm's law and the voltage. So, I will say that the voltage doesn't matter as far as the sensor is behave in the same way during calibration (R0) and during sampling (RL).

You can also check the input voltage to ensure that the input voltage on the VCC (not the heater) is consistant with your expectations. My experience is that the cause of the issue is often on the input voltage ;-).
